### ISSUE TITLE
Making the page size scale with the Navigation Bar

### ISSUE THREAD

**Issue by rudera** [Tempoture/Tempoture-Frontend#8]
As of now when you open the navigation bar the page size does not scale with it; this needs to change

**Comment by crowlc3** [comment]
![94a5ba59-ad06-46e2-badd-a120fd4643e9](https://user-images.githubusercontent.com/45721609/108615463-6634e100-73d2-11eb-864a-4c214a779f53.gif)


I was originally planning on doing a rework of the nav bar but this way ended up being the best so I just changed a css variable when the nav bar was active/inactive
